[workspace]
resolver = "3"
members = ["crates/*"]
# 直接 `cargo run` 就跑主程序，不用写 -p
default-members = ["crates/pliers-ime"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
wayland-client = "0.31"
wayland-protocols-misc = { version = "0.3", features = ["client"] }
xkbcommon = "0.7"

pliers-engine = { path = "crates/pliers-engine" }
pliers-popup = { path = "crates/pliers-popup" }
pliers-wayland = { path = "crates/pliers-wayland" }
